/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace SealedBidAuction {
  export type BidStruct = {
    bidder: AddressLike;
    amount: BigNumberish;
    timestamp: BigNumberish;
    deposit: BigNumberish;
  };

  export type BidStructOutput = [
    bidder: string,
    amount: bigint,
    timestamp: bigint,
    deposit: bigint
  ] & { bidder: string; amount: bigint; timestamp: bigint; deposit: bigint };
}

export interface SealedBidAuctionInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BID_EXTENSION_TIME"
      | "CLAIM_DURATION"
      | "MAX_AUCTION_DURATION"
      | "MAX_BIDS_PER_AUCTION"
      | "MAX_COLLECTION_SIZE"
      | "MAX_EXTENSIONS"
      | "MIN_AUCTION_DURATION"
      | "MIN_BID_INCREMENT"
      | "PLATFORM_FEE"
      | "auctions"
      | "cancelAuction"
      | "claimNFT"
      | "createCollectionAuction"
      | "createSingleNFTAuction"
      | "finalizeAuction"
      | "getAuctionBids"
      | "onERC721Received"
      | "owner"
      | "placeBid"
      | "reclaimNFT"
      | "renounceOwnership"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AuctionCancelled"
      | "AuctionCreated"
      | "AuctionFinalized"
      | "BidPlaced"
      | "NFTClaimed"
      | "NFTReclaimed"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BID_EXTENSION_TIME",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CLAIM_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_AUCTION_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_BIDS_PER_AUCTION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_COLLECTION_SIZE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_EXTENSIONS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_AUCTION_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_BID_INCREMENT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PLATFORM_FEE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "auctions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelAuction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimNFT",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createCollectionAuction",
    values: [
      AddressLike,
      BigNumberish[],
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createSingleNFTAuction",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeAuction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAuctionBids",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "onERC721Received",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "placeBid",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "reclaimNFT",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "BID_EXTENSION_TIME",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CLAIM_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_AUCTION_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_BIDS_PER_AUCTION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_COLLECTION_SIZE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_EXTENSIONS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_AUCTION_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_BID_INCREMENT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PLATFORM_FEE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "auctions", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelAuction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claimNFT", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createCollectionAuction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createSingleNFTAuction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeAuction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAuctionBids",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onERC721Received",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "placeBid", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "reclaimNFT", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace AuctionCancelledEvent {
  export type InputTuple = [
    auctionId: BigNumberish,
    seller: AddressLike,
    reason: string
  ];
  export type OutputTuple = [auctionId: bigint, seller: string, reason: string];
  export interface OutputObject {
    auctionId: bigint;
    seller: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AuctionCreatedEvent {
  export type InputTuple = [
    auctionId: BigNumberish,
    seller: AddressLike,
    nftContract: AddressLike,
    auctionType: BigNumberish,
    tokenId: BigNumberish,
    tokenIds: BigNumberish[],
    startingPrice: BigNumberish,
    endTime: BigNumberish,
    title: string
  ];
  export type OutputTuple = [
    auctionId: bigint,
    seller: string,
    nftContract: string,
    auctionType: bigint,
    tokenId: bigint,
    tokenIds: bigint[],
    startingPrice: bigint,
    endTime: bigint,
    title: string
  ];
  export interface OutputObject {
    auctionId: bigint;
    seller: string;
    nftContract: string;
    auctionType: bigint;
    tokenId: bigint;
    tokenIds: bigint[];
    startingPrice: bigint;
    endTime: bigint;
    title: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AuctionFinalizedEvent {
  export type InputTuple = [
    auctionId: BigNumberish,
    winner: AddressLike,
    finalPrice: BigNumberish,
    platformFeeAmount: BigNumberish,
    sellerAmount: BigNumberish
  ];
  export type OutputTuple = [
    auctionId: bigint,
    winner: string,
    finalPrice: bigint,
    platformFeeAmount: bigint,
    sellerAmount: bigint
  ];
  export interface OutputObject {
    auctionId: bigint;
    winner: string;
    finalPrice: bigint;
    platformFeeAmount: bigint;
    sellerAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BidPlacedEvent {
  export type InputTuple = [
    auctionId: BigNumberish,
    bidder: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    auctionId: bigint,
    bidder: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    auctionId: bigint;
    bidder: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NFTClaimedEvent {
  export type InputTuple = [
    auctionId: BigNumberish,
    winner: AddressLike,
    amountPaid: BigNumberish
  ];
  export type OutputTuple = [
    auctionId: bigint,
    winner: string,
    amountPaid: bigint
  ];
  export interface OutputObject {
    auctionId: bigint;
    winner: string;
    amountPaid: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NFTReclaimedEvent {
  export type InputTuple = [auctionId: BigNumberish, seller: AddressLike];
  export type OutputTuple = [auctionId: bigint, seller: string];
  export interface OutputObject {
    auctionId: bigint;
    seller: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SealedBidAuction extends BaseContract {
  connect(runner?: ContractRunner | null): SealedBidAuction;
  waitForDeployment(): Promise<this>;

  interface: SealedBidAuctionInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BID_EXTENSION_TIME: TypedContractMethod<[], [bigint], "view">;

  CLAIM_DURATION: TypedContractMethod<[], [bigint], "view">;

  MAX_AUCTION_DURATION: TypedContractMethod<[], [bigint], "view">;

  MAX_BIDS_PER_AUCTION: TypedContractMethod<[], [bigint], "view">;

  MAX_COLLECTION_SIZE: TypedContractMethod<[], [bigint], "view">;

  MAX_EXTENSIONS: TypedContractMethod<[], [bigint], "view">;

  MIN_AUCTION_DURATION: TypedContractMethod<[], [bigint], "view">;

  MIN_BID_INCREMENT: TypedContractMethod<[], [bigint], "view">;

  PLATFORM_FEE: TypedContractMethod<[], [bigint], "view">;

  auctions: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        string,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        string,
        string,
        bigint
      ] & {
        auctionId: bigint;
        auctionType: bigint;
        nftContract: string;
        tokenId: bigint;
        seller: string;
        startingPrice: bigint;
        reservePrice: bigint;
        minBidIncrement: bigint;
        startTime: bigint;
        endTime: bigint;
        bidExtensionTime: bigint;
        state: bigint;
        totalBids: bigint;
        highestBidder: string;
        highestBid: bigint;
        title: string;
        description: string;
        claimDeadline: bigint;
      }
    ],
    "view"
  >;

  cancelAuction: TypedContractMethod<
    [auctionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimNFT: TypedContractMethod<[auctionId: BigNumberish], [void], "payable">;

  createCollectionAuction: TypedContractMethod<
    [
      nftContract: AddressLike,
      tokenIds: BigNumberish[],
      startingPrice: BigNumberish,
      reservePrice: BigNumberish,
      minBidIncrement: BigNumberish,
      duration: BigNumberish,
      title: string,
      description: string
    ],
    [bigint],
    "nonpayable"
  >;

  createSingleNFTAuction: TypedContractMethod<
    [
      nftContract: AddressLike,
      tokenId: BigNumberish,
      startingPrice: BigNumberish,
      reservePrice: BigNumberish,
      minBidIncrement: BigNumberish,
      duration: BigNumberish,
      title: string,
      description: string
    ],
    [bigint],
    "nonpayable"
  >;

  finalizeAuction: TypedContractMethod<
    [auctionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getAuctionBids: TypedContractMethod<
    [auctionId: BigNumberish],
    [SealedBidAuction.BidStructOutput[]],
    "view"
  >;

  onERC721Received: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BytesLike],
    [string],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  placeBid: TypedContractMethod<
    [auctionId: BigNumberish, bidAmount: BigNumberish],
    [void],
    "payable"
  >;

  reclaimNFT: TypedContractMethod<
    [auctionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BID_EXTENSION_TIME"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "CLAIM_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_AUCTION_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_BIDS_PER_AUCTION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_COLLECTION_SIZE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_EXTENSIONS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_AUCTION_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_BID_INCREMENT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PLATFORM_FEE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "auctions"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        string,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        string,
        string,
        bigint
      ] & {
        auctionId: bigint;
        auctionType: bigint;
        nftContract: string;
        tokenId: bigint;
        seller: string;
        startingPrice: bigint;
        reservePrice: bigint;
        minBidIncrement: bigint;
        startTime: bigint;
        endTime: bigint;
        bidExtensionTime: bigint;
        state: bigint;
        totalBids: bigint;
        highestBidder: string;
        highestBid: bigint;
        title: string;
        description: string;
        claimDeadline: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "cancelAuction"
  ): TypedContractMethod<[auctionId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimNFT"
  ): TypedContractMethod<[auctionId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "createCollectionAuction"
  ): TypedContractMethod<
    [
      nftContract: AddressLike,
      tokenIds: BigNumberish[],
      startingPrice: BigNumberish,
      reservePrice: BigNumberish,
      minBidIncrement: BigNumberish,
      duration: BigNumberish,
      title: string,
      description: string
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createSingleNFTAuction"
  ): TypedContractMethod<
    [
      nftContract: AddressLike,
      tokenId: BigNumberish,
      startingPrice: BigNumberish,
      reservePrice: BigNumberish,
      minBidIncrement: BigNumberish,
      duration: BigNumberish,
      title: string,
      description: string
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "finalizeAuction"
  ): TypedContractMethod<[auctionId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAuctionBids"
  ): TypedContractMethod<
    [auctionId: BigNumberish],
    [SealedBidAuction.BidStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "onERC721Received"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish, arg3: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "placeBid"
  ): TypedContractMethod<
    [auctionId: BigNumberish, bidAmount: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "reclaimNFT"
  ): TypedContractMethod<[auctionId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AuctionCancelled"
  ): TypedContractEvent<
    AuctionCancelledEvent.InputTuple,
    AuctionCancelledEvent.OutputTuple,
    AuctionCancelledEvent.OutputObject
  >;
  getEvent(
    key: "AuctionCreated"
  ): TypedContractEvent<
    AuctionCreatedEvent.InputTuple,
    AuctionCreatedEvent.OutputTuple,
    AuctionCreatedEvent.OutputObject
  >;
  getEvent(
    key: "AuctionFinalized"
  ): TypedContractEvent<
    AuctionFinalizedEvent.InputTuple,
    AuctionFinalizedEvent.OutputTuple,
    AuctionFinalizedEvent.OutputObject
  >;
  getEvent(
    key: "BidPlaced"
  ): TypedContractEvent<
    BidPlacedEvent.InputTuple,
    BidPlacedEvent.OutputTuple,
    BidPlacedEvent.OutputObject
  >;
  getEvent(
    key: "NFTClaimed"
  ): TypedContractEvent<
    NFTClaimedEvent.InputTuple,
    NFTClaimedEvent.OutputTuple,
    NFTClaimedEvent.OutputObject
  >;
  getEvent(
    key: "NFTReclaimed"
  ): TypedContractEvent<
    NFTReclaimedEvent.InputTuple,
    NFTReclaimedEvent.OutputTuple,
    NFTReclaimedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "AuctionCancelled(uint256,address,string)": TypedContractEvent<
      AuctionCancelledEvent.InputTuple,
      AuctionCancelledEvent.OutputTuple,
      AuctionCancelledEvent.OutputObject
    >;
    AuctionCancelled: TypedContractEvent<
      AuctionCancelledEvent.InputTuple,
      AuctionCancelledEvent.OutputTuple,
      AuctionCancelledEvent.OutputObject
    >;

    "AuctionCreated(uint256,address,address,uint8,uint256,uint256[],uint256,uint256,string)": TypedContractEvent<
      AuctionCreatedEvent.InputTuple,
      AuctionCreatedEvent.OutputTuple,
      AuctionCreatedEvent.OutputObject
    >;
    AuctionCreated: TypedContractEvent<
      AuctionCreatedEvent.InputTuple,
      AuctionCreatedEvent.OutputTuple,
      AuctionCreatedEvent.OutputObject
    >;

    "AuctionFinalized(uint256,address,uint256,uint256,uint256)": TypedContractEvent<
      AuctionFinalizedEvent.InputTuple,
      AuctionFinalizedEvent.OutputTuple,
      AuctionFinalizedEvent.OutputObject
    >;
    AuctionFinalized: TypedContractEvent<
      AuctionFinalizedEvent.InputTuple,
      AuctionFinalizedEvent.OutputTuple,
      AuctionFinalizedEvent.OutputObject
    >;

    "BidPlaced(uint256,address,uint256)": TypedContractEvent<
      BidPlacedEvent.InputTuple,
      BidPlacedEvent.OutputTuple,
      BidPlacedEvent.OutputObject
    >;
    BidPlaced: TypedContractEvent<
      BidPlacedEvent.InputTuple,
      BidPlacedEvent.OutputTuple,
      BidPlacedEvent.OutputObject
    >;

    "NFTClaimed(uint256,address,uint256)": TypedContractEvent<
      NFTClaimedEvent.InputTuple,
      NFTClaimedEvent.OutputTuple,
      NFTClaimedEvent.OutputObject
    >;
    NFTClaimed: TypedContractEvent<
      NFTClaimedEvent.InputTuple,
      NFTClaimedEvent.OutputTuple,
      NFTClaimedEvent.OutputObject
    >;

    "NFTReclaimed(uint256,address)": TypedContractEvent<
      NFTReclaimedEvent.InputTuple,
      NFTReclaimedEvent.OutputTuple,
      NFTReclaimedEvent.OutputObject
    >;
    NFTReclaimed: TypedContractEvent<
      NFTReclaimedEvent.InputTuple,
      NFTReclaimedEvent.OutputTuple,
      NFTReclaimedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
