# Railway deployment configuration for persistent listeners
[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm run listeners"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
