# Railway deployment configuration for Next.js frontend
[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm run start: listeners"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production.variables]
NODE_ENV = "production"
NEXT_PUBLIC_API_URL = "https://safirx-premium-production.up.railway.app"
