# Railway deployment configuration for Next.js frontend
[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm run start:listeners"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
# Explicitly disable pre-deploy command
preDeployCommand = ""

[environments.production.variables]
NODE_ENV = "production"
NEXT_PUBLIC_API_URL = "https://safirx-premium-production.up.railway.app"
