/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as marketPlaceSol from "./marketPlace.sol";
export type { marketPlaceSol };
import type * as mintNftSol from "./mintNFT.sol";
export type { mintNftSol };
import type * as sealedBidAuctionSol from "./sealedBidAuction.sol";
export type { sealedBidAuctionSol };
